using System.Collections.Generic;
using Steamworks;
using UnityEngine;

namespace LunacidCoopMod
{
    // Identity record for one peer in the host's lobby. Slot 0 is host, 1..MAX_SLOTS-1 are clients.
    public struct ClientSlot
    {
        public int Slot;
        public CSteamID SteamId;    // Nil in local-test mode
        public string PlayerName;
        public string PlayerId;     // session GUID generated by the peer
        public float JoinTime;
    }

    // Host-side mapping of slot index to peer identity.
    // Allocation is always lowest free client slot; slots are not owned by any specific player.
    public class SlotTable
    {
        public const int MAX_SLOTS = 4;   // host + 3 clients
        public const int HOST_SLOT = 0;

        private readonly Dictionary<int, ClientSlot> bySlot     = new Dictionary<int, ClientSlot>();
        private readonly Dictionary<CSteamID, int>   byId       = new Dictionary<CSteamID, int>();
        private readonly Dictionary<string, int>     byPlayerId = new Dictionary<string, int>();

        // Total occupied slots (host + connected clients).
        public int Count => bySlot.Count;

        // Connected clients only (excludes host).
        public int ClientCount => bySlot.Count - (bySlot.ContainsKey(HOST_SLOT) ? 1 : 0);

        // Populate slot 0 with the host's identity. Idempotent.
        public void SetHostSlot(CSteamID hostId, string hostName, string hostPlayerId)
        {
            // Drop any prior host entry from lookups before overwriting.
            if (bySlot.TryGetValue(HOST_SLOT, out var prev))
            {
                byId.Remove(prev.SteamId);
                if (!string.IsNullOrEmpty(prev.PlayerId)) byPlayerId.Remove(prev.PlayerId);
            }

            bySlot[HOST_SLOT] = new ClientSlot
            {
                Slot       = HOST_SLOT,
                SteamId    = hostId,
                PlayerName = hostName,
                PlayerId   = hostPlayerId,
                JoinTime   = Time.time
            };
            byId[hostId] = HOST_SLOT;
            if (!string.IsNullOrEmpty(hostPlayerId)) byPlayerId[hostPlayerId] = HOST_SLOT;
        }

        // Assign the lowest free client slot to this peer. Returns -1 if full.
        public int AllocateSlot(CSteamID steamId, string playerName, string playerId)
        {
            for (int s = HOST_SLOT + 1; s < MAX_SLOTS; s++)
            {
                if (bySlot.ContainsKey(s)) continue;

                bySlot[s] = new ClientSlot
                {
                    Slot       = s,
                    SteamId    = steamId,
                    PlayerName = playerName,
                    PlayerId   = playerId,
                    JoinTime   = Time.time
                };
                byId[steamId] = s;
                if (!string.IsNullOrEmpty(playerId)) byPlayerId[playerId] = s;
                return s;
            }
            return -1;
        }

        // Free a client slot by SteamID. Host slot is never freed. Returns true on success.
        public bool FreeSlot(CSteamID steamId)
        {
            if (!byId.TryGetValue(steamId, out int slot)) return false;
            if (slot == HOST_SLOT) return false;
            return FreeSlotInternal(slot);
        }

        public bool FreeSlotByIndex(int slot)
        {
            if (slot == HOST_SLOT) return false;
            return FreeSlotInternal(slot);
        }

        private bool FreeSlotInternal(int slot)
        {
            if (!bySlot.TryGetValue(slot, out var entry)) return false;
            bySlot.Remove(slot);
            byId.Remove(entry.SteamId);
            if (!string.IsNullOrEmpty(entry.PlayerId)) byPlayerId.Remove(entry.PlayerId);
            return true;
        }

        public bool TryGetSlot(CSteamID steamId, out int slot) => byId.TryGetValue(steamId, out slot);

        public bool TryGetByPlayerId(string playerId, out ClientSlot entry)
        {
            if (string.IsNullOrEmpty(playerId) || !byPlayerId.TryGetValue(playerId, out int slot))
            {
                entry = default;
                return false;
            }
            return bySlot.TryGetValue(slot, out entry);
        }

        public bool TryGetByIndex(int slot, out ClientSlot entry) => bySlot.TryGetValue(slot, out entry);

        // New list of all occupied slots, ordered by slot index (host first).
        public List<ClientSlot> Snapshot()
        {
            var list = new List<ClientSlot>(bySlot.Count);
            for (int s = 0; s < MAX_SLOTS; s++)
            {
                if (bySlot.TryGetValue(s, out var entry)) list.Add(entry);
            }
            return list;
        }

        // Iterate non-host slots only. Used for "send to all clients" loops.
        public IEnumerable<ClientSlot> Clients()
        {
            for (int s = HOST_SLOT + 1; s < MAX_SLOTS; s++)
            {
                if (bySlot.TryGetValue(s, out var entry)) yield return entry;
            }
        }

        public void Clear()
        {
            bySlot.Clear();
            byId.Clear();
            byPlayerId.Clear();
        }
    }
}
